"""The agent's hands: ordering through the Friends Kitchen REST API.

These mirror the screens a human touches — browse, add, cart, coupon, pay — so
that swapping in the browser toolset later changes *how* the agent acts, not
what it knows how to do.

Two rules run through all of them:

* Tool results stay small. Products carry `imgBase64` photos that would swamp
  the context window, so they never leave this module.
* Money is checked in `authorize_payment` against the wallet, not trusted to the
  prompt. See agent/wallet.py.

A third rule, about how money *leaves* here: the API deals in bare numbers, and
every one of them is already a rupee amount. They are formatted with `rupees()`
on the way out so the agent reads `Rs 1,093` and never has to decide for itself
whether `1093` is rupees, paisa or dollars. The raw numbers stay in `_order` and
the wallet, where the arithmetic happens.
"""

from __future__ import annotations

from typing import Any

from strands import tool

from agent import kiosk_api
from agent.cart import cart
from agent.kiosk_api import KioskApiError
from agent.wallet import BudgetExceeded, money, rupees, wallet

# The order placed this run: {orderId, orderNumber, amountDue, ...}. Set by
# place_order, read by the coupon and payment tools so the agent never has to
# carry an id around in prose.
_order: dict[str, Any] = {}


def reset() -> None:
    """Forget the previous errand — the cart and the order it produced."""
    cart.clear()
    _order.clear()


def _slim_product(product: dict) -> dict:
    """A product as the agent should see it — no artwork, no modifier plumbing."""
    return {
        "productId": product["id"],
        "name": product["name"],
        "description": product.get("description", ""),
        "price": rupees(product["price"]),
        "calories": product.get("calories", 0),
        "categoryId": product.get("categoryId"),
        "isMealEligible": product.get("isMealEligible", False),
        "badge": product.get("badge"),
    }


def _fail(message: str) -> dict:
    return {"ok": False, "error": message}


# --------------------------------------------------------------------------- #
# Menu
# --------------------------------------------------------------------------- #
@tool
def browse_menu(search: str = "", category_id: str = "") -> dict:
    """Look at the restaurant's menu.

    Call this first — product ids are generated by the restaurant and cannot be
    guessed. Use `search` to find something the customer named ("burger",
    "fries"); leave both arguments empty to see everything.

    Args:
        search: Case-insensitive match against product name and description.
        category_id: Restrict to one category id from list_categories.

    Returns:
        Matching products with their ids, names and prices, written as `Rs 450`.
    """
    try:
        if category_id:
            products = kiosk_api.get(f"/categories/{category_id}/products")
        else:
            products = kiosk_api.get("/products")
    except KioskApiError as exc:
        return _fail(str(exc))

    items = [_slim_product(p) for p in products]

    if search:
        needle = search.lower()
        matched = [
            item
            for item in items
            if needle in item["name"].lower() or needle in item["description"].lower()
        ]
        # An empty result is a dead end for the agent, so hand back the whole
        # menu instead and say why — it can pick the nearest thing itself.
        if not matched:
            return {
                "ok": True,
                "matched": 0,
                "note": f"Nothing matched {search!r}. Showing the full menu instead.",
                "products": items,
            }
        items = matched

    return {"ok": True, "matched": len(items), "products": items}


@tool
def list_categories() -> dict:
    """List the menu's categories (Burgers, Sides, Drinks, and so on).

    Returns:
        Category ids and names, for narrowing a later browse_menu call.
    """
    try:
        categories = kiosk_api.get("/categories")
    except KioskApiError as exc:
        return _fail(str(exc))

    return {
        "ok": True,
        "categories": [{"categoryId": c["id"], "name": c["name"]} for c in categories],
    }


# --------------------------------------------------------------------------- #
# Cart
# --------------------------------------------------------------------------- #
@tool
def add_to_cart(product_id: str, quantity: int = 1, as_meal: bool = False) -> dict:
    """Put an item in the cart.

    Args:
        product_id: An id from browse_menu — not the product's name.
        quantity: How many, 1 or more.
        as_meal: Upgrade to a meal (adds fries and a drink for an upcharge).
            Only valid when the product's isMealEligible is true.

    Returns:
        The cart after the addition.
    """
    if quantity < 1:
        return _fail("Quantity must be at least 1.")

    try:
        product = kiosk_api.get(f"/products/{product_id}")
    except KioskApiError as exc:
        return _fail(
            f"{exc} Call browse_menu to get a valid product id — ids are not the product name."
        )

    if as_meal and not product.get("isMealEligible", False):
        return _fail(f"{product['name']} cannot be made a meal. Add it on its own.")

    line = cart.add(
        product_id=product["id"],
        name=product["name"],
        unit_price=product["price"],
        quantity=quantity,
        is_meal=as_meal,
    )
    return {
        "ok": True,
        "added": line.to_view(),
        "cart": cart.to_view(),
    }


@tool
def view_cart() -> dict:
    """Show what is in the cart right now, with an estimated subtotal.

    Returns:
        The cart lines, item count and estimated subtotal in rupees.
    """
    return {"ok": True, "cart": cart.to_view()}


@tool
def remove_from_cart(line_id: str) -> dict:
    """Take a line back out of the cart.

    Args:
        line_id: The lineId shown by view_cart.

    Returns:
        The cart after the removal.
    """
    if not cart.remove(line_id):
        return _fail(f"No cart line {line_id!r}. Call view_cart to see the current lineIds.")
    return {"ok": True, "cart": cart.to_view()}


# --------------------------------------------------------------------------- #
# Coupon — the token the agent was sent with
# --------------------------------------------------------------------------- #
@tool
def check_coupon() -> dict:
    """Ask the restaurant whether the coupon you were given is usable, and what
    it would take off the current cart.

    Worth calling before checkout: a product coupon only applies when a product
    it covers is actually in the cart, and this says so while the cart can still
    be changed.

    Returns:
        Whether the coupon is valid, what it would cover in rupees, and why not
        if not.
    """
    if not wallet.coupon_code:
        return _fail("No coupon was issued for this errand — pay with the cash limit instead.")
    if not cart.lines:
        return _fail("The cart is empty, so there is nothing for the coupon to apply to.")

    try:
        result = kiosk_api.post(
            "/coupons/validate",
            {
                "couponCode": wallet.coupon_code,
                "orderAmount": cart.subtotal,
                "allowPartial": True,
                "cartLines": cart.to_coupon_lines(),
            },
        )
    except KioskApiError as exc:
        return _fail(str(exc))

    return {
        "ok": True,
        "valid": result.get("valid", False),
        "reason": result.get("reasonMessage"),
        "couponType": result.get("couponType"),
        "wouldCover": rupees(result.get("applicableAmount") or 0),
        "remainingBalance": money(result.get("remainingBalance")),
        "matchedProductIds": result.get("matchedProductIds", []),
    }


# --------------------------------------------------------------------------- #
# Checkout
# --------------------------------------------------------------------------- #
@tool
def place_order(order_type: str = "take_away", payment_method: str = "card") -> dict:
    """Send the cart to the kitchen. This creates the order but does not pay for
    it — the coupon goes on next, then payment.

    Args:
        order_type: "dine_in" or "take_away".
        payment_method: "card", "wallet" or "counter".

    Returns:
        The order number, its real total, and what is left to pay — every
        amount already written as `Rs 1,093`.
    """
    if not cart.lines:
        return _fail("The cart is empty. Add something before placing an order.")
    if order_type not in ("dine_in", "take_away"):
        return _fail("order_type must be 'dine_in' or 'take_away'.")
    if payment_method not in ("card", "wallet", "counter"):
        return _fail("payment_method must be 'card', 'wallet' or 'counter'.")

    try:
        placed = kiosk_api.post(
            "/orders",
            {
                "orderType": order_type,
                "paymentMethod": payment_method,
                "lines": cart.to_api_lines(),
            },
        )
    except KioskApiError as exc:
        return _fail(str(exc))

    summary = placed["summary"]
    _order.clear()
    _order.update(
        {
            "orderId": placed["orderId"],
            "orderNumber": placed["orderNumber"],
            "paymentMethod": placed["paymentMethod"],
            "total": summary["total"],
            "amountDue": summary.get("amountDue") or summary["total"],
        }
    )

    return {
        "ok": True,
        "orderNumber": placed["orderNumber"],
        "status": placed["status"],
        "subtotal": rupees(summary["subtotal"]),
        "tax": rupees(summary["tax"]),
        "total": rupees(summary["total"]),
        "amountDue": rupees(_order["amountDue"]),
        "next": "Apply the coupon with apply_coupon, then call authorize_payment.",
    }


@tool
def apply_coupon() -> dict:
    """Redeem your coupon against the order you just placed, before paying.

    A product coupon discounts the line it covers and is spent in full; a value
    coupon draws what it can and keeps the rest for next time.

    Returns:
        How much came off and what is still to pay, both in rupees.
    """
    if not _order:
        return _fail("No order has been placed yet — call place_order first.")
    if not wallet.coupon_code:
        return _fail("No coupon was issued for this errand.")

    try:
        redemption = kiosk_api.post(
            "/coupons/redeem",
            {
                "couponCode": wallet.coupon_code,
                "orderId": _order["orderId"],
                "allowPartial": True,
                "customerId": wallet.customer_id,
            },
        )
    except KioskApiError as exc:
        return _fail(
            f"{exc} The order is still unpaid — you can pay the full amount with "
            "authorize_payment if it fits your cash limit."
        )

    wallet.record_coupon(redemption["redeemedAmount"])
    _order["amountDue"] = redemption["amountDue"]

    return {
        "ok": True,
        "redeemed": rupees(redemption["redeemedAmount"]),
        "couponStatus": redemption["status"],
        "remainingCouponBalance": money(redemption.get("remainingBalance")),
        "orderTotal": rupees(redemption["orderTotal"]),
        "amountDue": rupees(redemption["amountDue"]),
    }


@tool
def authorize_payment() -> dict:
    """Pay whatever is still owed on the order and finish the errand.

    This is the only tool that spends money, and it will refuse if the amount is
    more than the cash limit you were sent with. If it refuses, remove items or
    apply the coupon first — do not try to pay again unchanged.

    Returns:
        The approval, the amount charged in rupees, and what is left in the
        wallet.
    """
    if not _order:
        return _fail("No order has been placed yet — call place_order first.")

    amount_due = _order.get("amountDue", _order.get("total", 0))

    try:
        wallet.check(amount_due)
    except BudgetExceeded as exc:
        return _fail(str(exc))

    try:
        result = kiosk_api.post(
            "/payments",
            {"orderNumber": _order["orderNumber"], "method": _order["paymentMethod"]},
        )
    except KioskApiError as exc:
        return _fail(str(exc))

    if not result.get("approved", False):
        return _fail(
            f"The payment was declined ({result.get('status')}). The order is placed but unpaid."
        )

    charged = result.get("amount", amount_due)
    wallet.spend(charged)
    _order["amountDue"] = 0

    return {
        "ok": True,
        "approved": True,
        "orderNumber": result["orderNumber"],
        "charged": rupees(charged),
        "transactionRef": result.get("transactionRef"),
        "wallet": wallet.display(),
    }


@tool
def get_order(order_number: str = "") -> dict:
    """Look up an order — useful to confirm it really is paid before reporting back.

    Args:
        order_number: Defaults to the order placed during this errand.

    Returns:
        The order's status, totals and payment attempts.
    """
    number = order_number or _order.get("orderNumber", "")
    if not number:
        return _fail("No order number to look up.")

    try:
        detail = kiosk_api.get(f"/orders/number/{number}")
    except KioskApiError as exc:
        return _fail(str(exc))

    return {
        "ok": True,
        "orderNumber": detail["orderNumber"],
        "status": detail["status"],
        "total": rupees(detail["summary"]["total"]),
        "couponDiscount": rupees(detail["summary"].get("couponDiscount") or 0),
        "amountDue": rupees(detail["summary"].get("amountDue") or 0),
        "items": [
            {
                "name": line["name"],
                "quantity": line["quantity"],
                "lineTotal": rupees(line["lineTotal"]),
            }
            for line in detail["lines"]
        ],
        "payments": [
            {"method": p["method"], "status": p["status"], "amount": rupees(p["amount"])}
            for p in detail.get("payments", [])
        ],
    }


API_TOOLS = [
    list_categories,
    browse_menu,
    add_to_cart,
    view_cart,
    remove_from_cart,
    check_coupon,
    place_order,
    apply_coupon,
    authorize_payment,
    get_order,
]
